import streamlit as st
import pandas as pd
import requests
from datetime import datetime, date
import io
import time

# --- 1. SETTING AWAL ---
st.set_page_config(page_title="SUPS HJEM V8.7", layout="wide")

if 'bakul' not in st.session_state:
    st.session_state.bakul = []

URL_API = "https://script.google.com/macros/s/AKfycbyeZXuPoyqsORGh_-kPC8lVTiFe41qZvQ4V8gBQU_BXnmP30zufcjSDxN6HnqyzQRRu/exec"
URL_SHEET_CSV = "https://docs.google.com/spreadsheets/d/18K_lW1HUvA28cG6b5tf9RR3ckF8ONyALzDejvMhTvtI/export?format=csv"

# --- 2. MASTER LIST UBAT LENGKAP ---
MASTER_UBAT = sorted([
    "Abacavir 300mg Tablet", "Abacavir Sulphate 600mg + Lamivudine 300mg Tablet", "Acarbose 50 mg Tablet", 
    "Acetazolamide 250 mg Tablet", "Acetylsalicylic Acid 100 mg, Glycine 45 mg Tablet", "Acetylsalicylic Acid 150 mg Dispersible Tablet", 
    "Acetylsalicylic Acid 300 mg Soluble Tablet", "Acitretin 25mg Capsule", "Acriflavine 0.1% Lotion", 
    "Acyclovir 5% Cream", "Acyclovir 200 mg Tablet", "Acyclovir 800 mg Tablet", "Adadapalene 0.1% Gel", 
    "Agomelatine 25mg Tablet", "Albendazole 200 mg Tablet", "Albendazole 200 mg/5 ml Suspension", "Alcohol 70% Solution", 
    "Alcohol 96% (For External Use Only)", "Alcohol 96% (For Internal Use Only)", "Alendronate Sodium 70 mg Tablet", 
    "Alendronate Sodium 70 mg and Cholecalciferol 5600 IU Tablet", "Alfuzosin HCl 10 mg Tablet", "Alkaline Nasal Douche", 
    "Allopurinol 100 mg Tablet", "Allopurinol 300 mg Tablet", "Alprazolam 0.25 mg Tablet", "Alprazolam 0.5 mg Tablet", 
    "Amiloride HCl 5 mg + Hydrochlorothiazide 50 mg Tablet", "Amisulpride 400 mg Tablet", "Amitriptyline HCl 25 mg Tablet", 
    "Amlodipine 5 mg Tablet", "Amlodipine 10 mg Tablet", "Amlodipine 10 mg and Valsartan 160 mg Tablet", 
    "Amlodipine 10mg/Valsartan 160mg/Hydrochlorothiazide 25mg Tab", "Amoxicillin 250mg Capsule", "Amoxicillin 500mg Capsule", 
    "Amoxicillin 250mg/5mL Oral Solution", "Amoxicillin Trihydrate 125 mg/5 ml Syrup", "Amoxicillin 500 mg + Clavulanate 125 mg Tablet", 
    "Amoxicillin + Clavulanate 228 mg/5 ml Syrup", "Amorolfine 5 % Nail Lacquer", "Ampicillin + Sulbactam 375mg Tab", 
    "Apixaban 2.5 mg Film-coated Tablet", "Apixaban 5 mg Film-coated Tablet", "Aqueous Cream", "Aripiprazole 10mg Tablet", 
    "Artificial Tears/Eye Lubricant Ophthalmic Gel", "Artificial Tears/Eye Lubricant Ophthalmic Solution", 
    "Artificial Tears/Eye Lubricant Ophthalmic Solution (Preservative Free)", "Artificial Tears/Eye Lubricant Ophthalmic Solution (Single Use)", 
    "Ascorbic Acid 100 mg Tablet", "Atenolol 50 mg Tablet", "Atenolol 100 mg Tablet", "Atorvastatin 20 mg Tablet", 
    "Atorvastatin 40 mg Tablet", "Atorvastatin 80 mg Tablet", "Atropine Sulphate 1mg/ml Injection", "Atropine Sulphate 1% Eye Drops", 
    "Azathioprine 50 mg Tablet", "Azithromycin 250 mg Tablet", "Baclofen 10 mg Tablet", "BCG Vaccine Freeze-Dried Inj", 
    "Beclomethasone Dipropionate 50 mcg/dose Nasal Spray", "Beclomethasone Dipropionate 100 mcg/dose Inhalation", 
    "Beclomethasone Dipr. 100mcg, Formoterol 6mcg Inhalation", "Benzathine Penicillin 2.4MIU (1.8g) Injection", 
    "Benzhexol 2 mg Tablet", "Benzoic Acid Compound Ointment (Whitfields)", "Benzoyl Peroxide 5% Gel", 
    "Benzydamine HCl 0.15% Solution (Difflam)", "Benzydamine HCl 0.15% Solution (Easiflam)", "Benzyl Benzoate 12.5% Emulsion (Child)", 
    "Benzyl Benzoate 25 % Emulsion (Adult)", "Benzyl Benzoate, Zinc Oxide & Balsam Peru Suppository (Anusol)", 
    "Betahistine Dihydrochloride 24mg Tablet", "Betamethasone 17-Valerate 0.025% (1 in 4) Cream", "Betamethasone 17-Valerate 0.05% (1 in 2) Cream", 
    "Betamethasone 17-Valerate 0.1% Cream", "Betamethasone 17-Valerate 0.1% Ointment", "Betamethasone Valerate 1 in 2 Ointment", 
    "Betamethasone Valerate 1 in 10 Ointment", "Betaxolol 0.25% Eye Suspension", "Bimatoprost 0.03% Ophthalmic Solution", 
    "Bisacodyl 5 mg Tablet", "Bisacodyl 10 mg Suppository", "Bisoprolol Fumarate 2.5 mg Tablet", "Bisoprolol Fumarate 5 mg Tablet", 
    "Brimonidine Tartrate 0.15% Ophthalmic Solution", "Brinzolamide 1%, Brimonidine 0.2% Ophthalmic Suspension", 
    "Bromhexine HCl 4 mg/5 ml Elixir", "Bromhexine HCl 8mg Tablet", "Bromocriptine Mesilate 2.5mg Tablet", "Bromocriptine Mesilate 5mg Tablet", 
    "Budesonide 64mcg Nasal Spray", "Budesonide 100mcg Nasal Spray", "Budesonide 200mcg/dose Inhalation (300 Doses)", 
    "Budesonide Pressurised Inhalation BP 200mcg", "Budesonide 160mcg and Formoterol 4.5mcg Turbuhaler (120doses)", 
    "Calamine Cream", "Calamine Lotion", "Calcipotriol 50 mcg/g + Betamethasone 0.5 mg/g Gel", "Calcipotriol 50 mcg/g + Betamethasone 0.5 mg/g Ointment", 
    "Calcitriol 0.25mcg Capsule", "Calcium Carbonate 500mg Tablet", "Calcium Gluconate 10% Injection", "Calcium Lactate 300mg Tablet", 
    "Calcium Polystyrene Sulphonate Powder, 5g/sachet", "Captopril 25mg Tablet", "Carbamazepine 200mg Tablet", 
    "Carbamazepine 200mg CR Tablet", "Carbamazepine 400mg CR Tablet", "Carbamide (Urea) 10 % Cream", "Carbimazole 5mg Tablet", 
    "Carvedilol 6.25mg Tablet", "Celecoxib 200mg Capsule", "Cephalexin Monohydrate 250mg Capsule", "Cephalexin Monohydrate 500mg Capsule", 
    "Ceftriaxone 500mg Injection", "Cefuroxime Axetil 125mg Tablet", "Cetirizine HCl 10mg Tablet", "Cetrimide 2% Lotion", 
    "Charcoal Activated 250mg Tablet", "Chloramphenicol 0.5% Eye Drops", "Chloramphenicol 1% Eye Ointment", "Chloramphenicol 5% w/v Ear Drops", 
    "Chlorhexidine 1:200 in Alcohol with Emollient", "Chlorhexidine 1 in 200 (0.5%) in Alcohol 70%", "Chlorhexidine 1 in 2000 (0.05%) in Alcohol 70%", 
    "Chlorhexidine Gluconate 0.2% Mouthwash", "Chlorhexidine Gluconate 5% Solution", "Chlorhexidine gluconate 1% Cream (Obstetric)", 
    "Chlorpheniramine Maleate 2 mg/5 ml Syrup", "Chlorpheniramine Maleate 4mg Tablet", "Chlorpheniramine 10mg/ml Injection", 
    "Chlorpromazine HCl 25 mg Tablet", "Chlorpromazine HCl 100 mg Tablet", "Cholecalciferol 25,000 IU per 1ml Oral Solution", 
    "Cinnarizine 25 mg Tablet", "Clobetasol Propionate 0.05% Cream", "Clobetasol Propionate 0.05% Ointment", 
    "Clobetasone Butyrate 0.05% Cream", "Clobetasone Butyrate 0.05% Ointment", "Clopidogrel 75 mg Tablet", 
    "Clotrimazole 1% Cream", "Clotrimazole 500 mg Vaginal Tablet", "Clozapine 100 mg Tablet", "Cloxacillin Sodium 125 mg/5 ml Suspension", 
    "Cloxacillin Sodium 250mg Capsule", "Cloxacillin 500mg Capsule", "Coal Tar (LPC) 3% Ointment", "Coal Tar (LPC) 6% Ointment", 
    "Coal Tar 12% Salicylic acid 2% Sulphur 4% Ointment", "Colchicine 0.5 mg Tablet", "Compound Zinc Paste BP (25%w/w)", 
    "Conjugated Oestrogens 0.625mg Tablet", "Copper Sulphate Crystal", "Crotamiton 10 % Cream", "Dabigatran Etexilate 110 mg Capsule", 
    "Dabigatran Etexilate 150 mg Capsule", "Daclatasvir 60mg Tablet", "Danazol 200 mg Capsule", "Dapagliflozin 10 mg Film-Coated Tablet", 
    "Dapsone 100 mg Tablet", "Desloratadine 5 mg Tablet", "Desvenlafaxine 50 mg EXTENDED RELEASE Tablet", "Dexamethasone Acetate 0.1% Eye Drop", 
    "Dexamethasone sodium phosphate 0.1% Eye Drops", "Dexamethasone,Neomycin,Polymyxin B Eye Drop (Maxitrol)", 
    "Dextrose 5% 500ml IV soln", "Dextrose 10% 500mL IV soln", "Dextrose 50% 10mL Inj", "Dextrose Powder", 
    "Diazepam 5 mg Rectal Solution", "Diazepam 10 mg/2 ml Injection", "Diclofenac 1% Emulgel", "Diclofenac Sodium 50 mg Tablet", 
    "Diclofenac Sodium 75mg/3 ml Injection", "Dienogest 2mg Tablet", "Digoxin 0.25 mg Tablet", "Diltiazem HCl 30 mg Tablet", 
    "Diosmin 450 mg and Hesperidin 50 mg Tablet", "Diphenhydramine HCl Expectorant (Adult)", "Diphenhydramine HCl Expectorant (Paediatric) 7mg/5ml", 
    "Diphenoxylate with Atropine Sulphate Tablet", "Diphtheria and Tetanus Vaccine", "Diptheria-Tetanus-Pertussis-IPV-Hib Vaccine", 
    "Distilled Water", "Dolutegravir 50 mg Tablet", "Domperidone 1 mg/ml Suspension", "Domperidone 10 mg Tablet", 
    "Donepezil HCl 5 mg Tablet", "Donepezil HCl 10 mg Tablet", "Dorzolamide HCl 2% Ophthalmic Solution", 
    "Dorzolamide 2%, Timolol 0.5% Eye drop", "Doxazosin Mesilate 4 mg CR Tablet", "Doxycycline 100 mg Capsule", 
    "Duloxetine 60 mg Capsule", "Dutasteride 0.5 mg Capsule", "Dutasteride 0.5mg and Tamsulosin 0.4mg Capsule", 
    "Dydrogesterone 10 mg Tablet", "Ear Wax Softener (Ear Drop)", "Efavirenz 200 mg Capsule/Tablet", "Efavirenz 600 mg Tablet", 
    "Empagliflozin 10 mg Tablet", "Empagliflozin 25 mg Tablet", "Emulsifying Ointment BP", "Enalapril 5 mg Tablet", 
    "Enalapril 10 mg Tablet", "Enalapril 20 mg Tablet", "Enoxaparin Sodium 20 mg Injection", "Enoxaparin Sodium 60 mg Injection", 
    "Entacapone 200 mg Tablet", "Eperisone HCl 50 mg Tablet", "Erythromycin Ethylsuccinate 200 mg/5 ml Suspension", 
    "Erythromycin Ethylsuccinate 400 mg Tablet", "Escitalopram 10 mg Tablet", "ESOMEprazole 40 mg Tablet", 
    "Estradiol 2mg + Norgestrel 0.5mg (Combo Pack)", "Ethambutol HCl 400 mg Tablet", "Ethinyloestradiol 30mcg + Levonorgestrel 150mcg Tab", 
    "Etonogestrel 68 mg Implant", "Etoricoxib 90 mg Tablet", "Etoricoxib 120 mg Tablet", "Ezetimibe 10 mg Tablet", 
    "Ezetimibe 10 mg + Simvastatin 20 mg Tablet", "Felodipine 10 mg EXTENDED RELEASE Tablet", "Fenofibrate 145mg Tablet", 
    "Fentanyl 25 mcg/h Transdermal Patch", "Ferric Ammonium Citrate 400mg/5ml (FAC)", "Ferrous 350mg, Folic 1mg, Vit C, B6, B12, Zinc Capsule", 
    "Ferrous CR 525mg, Folic 800mcg, Vit C, B-Complex Tablet", "Ferrous Fumarate 200 mg Tablet", 
    "Ferrous Iron (Elemental Iron > 100mg), Vitamin & Mineral Capsule", "Finasteride 5 mg Tablet", "Fluconazole 100 mg Capsule", 
    "Fludrocortisone Acetate 0.1 mg Tablet", "Flunarizine HCl 5 mg Capsule", "Fluoxetine HCl 20 mg Capsule/Tablet", 
    "Flupenthixol Decanoate Depot 20mg/ml lnjection", "Fluphenazine Decanoate 25mg/ml Inj", "Fluticasone Furoate 27.5 mcg/dose Nasal Spray (60 doses)", 
    "Fluticasone Furoate 27.5 mcg/dose Nasal Spray (120 doses)", "Fluticasone propionate 125 mcg/dose Evohaler (120doses)", 
    "Fluticasone Propionate 125 mcg/dose Inhalation (120doses)", "Fluvoxamine 50 mg Tablet", "Fluvoxamine 100 mg Tablet", 
    "Folic Acid 5 mg Tablet", "Frusemide 10mg/ml Injection (20mg/2ml)", "Frusemide 40 mg Tablet", "Fusidic Acid 2% Cream", 
    "Fusidic Acid 1% Eye Drops", "Fusidic Acid 2% in Betamethasone Valerate 0.1% Cream", "Gabapentin 300 mg Capsule", 
    "Gabapentin 600 mg Tablet", "Gamma Benzene Hexachloride 0.1 % Lotion", "Gamma Benzene Hexachloride 1% Lotion", 
    "Gemfibrozil 300 mg Capsule", "Glibenclamide 5 mg Tablet", "Gliclazide 30 mg MODIFIED RELEASE Tablet", 
    "Gliclazide 60 mg MODIFIED RELEASE Tablet", "Gliclazide 80 mg Tablet", "Glycerin (Liquid)", "Glycerine 25% in Aqueous Cream", 
    "Glycerin 25%, Sodium Chloride 15% Enema (Ravin)", "Glyceryl Trinitrate 0.5 mg Tablet", 
    "Glycopyrronium 50mcg Inhalation Powder Hard Capsules", "Griseofulvin 125mg Tablet", "Haloperidol 1.5 mg Tablet", 
    "Haloperidol 5mg Tablet", "Hepatitis B 10mcg HbsAg Vaccine (Pediatric)", "Hepatitis B 20mcg HbsAg Vaccine (Adult)", 
    "Hydrochlorothiazide 25 mg Tablet", "Hydrochlorothiazide 50 mg Tablet", "Hydrocortisone 1% Cream", "Hydrocortisone 10 mg Tablet", 
    "Hydrocortisone Sodium Succinate 100mg Injection", "Hydrogen Peroxide 5 volume (1.5%) Mouthwash", "Hydrogen Peroxide 20 volume Solution (6%)", 
    "Hydrogen Peroxide 130 Volume Liquid", "Hydroxychloroquine 200 mg Tablet (UNIQUIN)", "Hydroxychloroquine 200 mg Tablet (PLAQUENIL)", 
    "Hydroxychloroquine Sulphate 200 mg Film Coated Tablet", "Hydroxyurea 500 mg Capsule", "Hyoscine N-Butylbromide 1 mg/ml Liquid", 
    "Hyoscine N-Butylbromide 10 mg Tablet", "Hyoscine N-Butylbromide 20mg/ml Injection", "Hypromellose 0.3% Eye Drop (Preservative Free)", 
    "Hypromellose 0.3% Eye Drops (with preservative)", "Ibuprofen 200 mg Tablet", "Imatinib Mesylate 400 mg Tablet", 
    "Indacaterol maleate 150mcg Inhalation Capsule", "Indacaterol Maleate 110mcg & Glycopyrronium Bromide 50mcg Inhalation", 
    "Indomethacin 25 mg Capsule", "Industrial Methylated Spirit (96%) BP - IMS", "Insulin aspart (Novorapid) 100 IU/ml FlexPen", 
    "Insulin aspart 30%/aspart protamine 70%(NovoMix-30) 100 IU/ml FlexPen", "Insulin detemir (Levemir) 100 IU/ml FlexPen", 
    "Insulin glargine (Basalog One) 100 IU/ml Prefilled Pen", "Insulin glargine (Lantus) 100 IU/ml Pre-filled Pen", 
    "Insulin isophane (Insulatard) 100 IU/mL Penfill", "Insulin isophane (Insuman Basal) 100 IU/mL Penfill", 
    "Insulin lispro 25% /lispro protamin 75%(Humalog Mix-25) 100 IU/mL Penfill", "Insulin lispro 50% /lispro protamin 50%(Humalog Mix-50) 100 IU/mL Penfill", 
    "Insulin Recombinant Neutral Human Short-acting (Insugen-R) 100 IU/mL Penfill", 
    "Insulin Recombinant Neutral Synthetic Human Short-acting (Diabulyn-R) 100 IU/mL Penfill", 
    "Insulin Recombinant Synthetic Human, Intermediate-Acting (Insugen-N) 100 IU/mL Penfill", 
    "Insulin Recombinant Synthetic Human, Intermediate-Acting (Diabulyn-N) 100 IU/mL Penfill", 
    "Insulin Recombinant Synthetic Human, Premixed (Insugen-30/70) 100 IU/mL Penfill", 
    "Insulin Recombinant Synthetic Human, Premixed (Diabulyn-30/70) 100 IU/mL Penfill", "Insulin regular (Actrapid) 100 IU/mL Penfill", 
    "Insulin regular/isophane (Humulin 30/70) 100 IU/mL Penfill", "Insulin regular/isophane (Insuman Comb) 100 IU/mL Penfill", 
    "Insulin regular/isophane (Mixtard-30) 100 IU/mL Penfill", "Ipratropium Br 20 mcg Fenoterol 50 mcg/dose Inhalation", 
    "Ipratropium Bromide 0.025% Nebulising Soln (UDV)", "Irbesartan 150 mg Tablet", "Irbesartan 300 mg Tablet", 
    "Iron Dextran 50mg/ml Injection", "Isoniazid 100 mg Tablet", "Isosorbide Dinitrate 10 mg Tablet", "Isosorbide-5-Mononitrate 60 mg SR Tablet", 
    "Itraconazole 100 mg Capsule", "Ivabradine 5 mg Tablet", "Ketoprofen 2.5% Gel", "Ketorolac Tromethamine 0.5% Eye drops", 
    "Labetalol HCl 100 mg Tablet", "Labetalol HCl 200 mg Tablet", "Lactulose 3.35 g/5 ml Liquid", "Lamivudine 150 mg Tablet", 
    "Lamotrigine 50 mg Tablet", "Lamotrigine 100 mg Tablet", "Latanoprost 0.005% Eye Drops", "Leflunomide 10 mg Tablet", 
    "Leflunomide 20 mg Tablet", "Letrozole 2.5 mg Tablet", "Levetiracetam 500 mg Tablet", "Levodopa 200 mg, Benserazide 50 mg Tablet", 
    "Levodopa 100 mg, Carbidopa 25 mg + Entacapone 200 mg Tablet", "Levothyroxine Sodium 25 mcg Tablet", 
    "Levothyroxine Sodium 50 mcg Tablet", "Levothyroxine Sodium 100 mcg Tablet", "Lidocaine 2.5%-Chlorhexidine 0.5%-Triamcinolone 0.1% Gel/Lotion", 
    "Lignocaine 2% Jelly", "LIGNOcaine HCl (Lidocaine) 2% Injection (10ml)", "Liquid Paraffin", "Lithium Carbonate 300 mg Tablet", 
    "Lopinavir 200 mg and Ritonavir 50 mg Tablet", "Loratadine 1 mg/ml Syrup", "Loratadine 10 mg Tablet", "Lorazepam 1 mg Tablet", 
    "Losartan 50 mg Tablet (LOSAGEN)", "Losartan 50 mg Tablet", "Losartan 100 mg Tablet (LOSAGEN)", "Losartan 100 mg Tablet", 
    "Magnesium Sulphate 50% Injection", "Magnesium Trisilicate Mixture", "Magnesium Trisilicate Tablet", "Measles, Mumps Rubella Vaccine Live", 
    "Measles Rubella Virus Vaccine Live, Attenuated (10 Doses)", "Mecobalamin 500 mcg Tablet", 
    "Meclozine HCl 25 mg and Pyridoxine 50 mg Tablet", "Medroxyprogesterone Acetate 5 mg Tablet", "Mefenamic Acid 250 mg Capsule", 
    "Memantine HCI 10 mg Tablet", "Meningococcal ACYW 135 Vaccine (10 doses)", "Metformin HCl 500 mg Tablet", 
    "Metformin HCl 500 mg EXTENDED RELEASE Tablet", "Metformin HCl 750mg EXTENDED RELEASE Tablet", 
    "Metformin 500 mg and Glibenclamide 2.5 mg Tablet", "Metformin 500 mg and Glibenclamide 5 mg Tablet", "Methadone 5mg/ml Syrup", 
    "Methotrexate 2.5 mg Tablet", "Methyldopa 250 mg Tablet", "Methylphenidate HCl 10 mg Tablet", "Methyl Salicylate 25% Ointment", 
    "Metoclopramide HCl 10 mg Tablet", "Metoclopramide HCl 10mg/2ml Injection", "Metoprolol Tartrate 100 mg Tablet", 
    "Metronidazole 200 mg Tablet", "Miconazole 2% Cream", "Midazolam 5 mg/ml Injection", "Mirabegron 50 mg PROLONGED RELEASE Tablet", 
    "Mirtazapine 15 mg Orodispersible Tablet", "Mirtazapine 30 mg Orodispersible Tablet", "Mometasone Furoate 0.1% Cream", 
    "Mometasone Furoate 50 mcg Aqueous Nasal Spray (Axcel)", "Mometasone Furoate 50 mcg Aqueous Nasal Spray", 
    "Montelukast Sodium 10 mg Tablet", "Morphine HCl 10 mg/5 ml Solution", "Morphine Sulphate 10 mg/ml Injection", 
    "Multivitamin Drops for Infant/Paediatric", "Multivitamin Syrup", "Mupirocin 2% Ointment", "Mycophenolate Mofetil 500 mg tablet (MYCOFIT)", 
    "Naltrexone HCl 50 mg Tablet", "Neomycin 0.5% Cream", "Nepafenac 0.1% w/v Eye Suspension", "Nevirapine 200 mg Tablet", 
    "Nicotine 10 mg/ 16 hour Transdermal Patch", "Nicotine 15 mg/ 16 hour Transdermal Patch", "Nicotine 2 mg Gum", "Nicotine 4 mg Gum", 
    "Nifedipine 10 mg Tablet", "Nystatin 100,000 units/ml Suspension", "Nystatin 100,000 units/g Cream", "Olanzapine 5 mg Tablet", 
    "Olanzapine 10 mg Tablet", "Olanzapine 10 mg DISINTEGRATING Tablet", "Olopatadine HCl 0.2% Opthalmic Solution", 
    "Omeprazole 20 mg Capsule", "Oral Rehydration Salt", "Oseltamivir 75 mg Capsule", "Oxytocin 5U + Ergometrine 0.5mg/ml Inj", 
    "Oxytocin 10 units/ml Injection", "Paliperidone 75 mg Prolonged Release Injection", "Paliperidone 150 mg Prolonged Release Injection",
