import streamlit as st
import pandas as pd
import requests
from datetime import datetime, date
import io
import time

# --- 1. SETTING AWAL ---
st.set_page_config(page_title="SUPS HJEM V8.8", layout="wide")

if 'bakul' not in st.session_state:
    st.session_state.bakul = []

URL_API = "https://script.google.com/macros/s/AKfycbyeZXuPoyqsORGh_-kPC8lVTiFe41qZvQ4V8gBQU_BXnmP30zufcjSDxN6HnqyzQRRu/exec"
URL_SHEET_CSV = "https://docs.google.com/spreadsheets/d/18K_lW1HUvA28cG6b5tf9RR3ckF8ONyALzDejvMhTvtI/export?format=csv"

# --- 2. MASTER LIST UBAT LENGKAP ---
MASTER_UBAT = sorted([
    "Abacavir 300mg Tablet", "Abacavir Sulphate 600mg + Lamivudine 300mg Tablet", "Acarbose 50 mg Tablet", 
    "Acetazolamide 250 mg Tablet", "Acetylsalicylic Acid 100 mg, Glycine 45 mg Tablet", "Acetylsalicylic Acid 150 mg Dispersible Tablet", 
    "Acetylsalicylic Acid 300 mg Soluble Tablet", "Acitretin 25mg Capsule", "Acriflavine 0.1% Lotion", 
    "Acyclovir 5% Cream", "Acyclovir 200 mg Tablet", "Acyclovir 800 mg Tablet", "Adadapalene 0.1% Gel", 
    "Agomelatine 25mg Tablet", "Albendazole 200 mg Tablet", "Albendazole 200 mg/5 ml Suspension", "Alcohol 70% Solution", 
    "Alcohol 96% (For External Use Only)", "Alcohol 96% (For Internal Use Only)", "Alendronate Sodium 70 mg Tablet", 
    "Alendronate Sodium 70 mg and Cholecalciferol 5600 IU Tablet", "Alfuzosin HCl 10 mg Tablet", "Alkaline Nasal Douche", 
    "Allopurinol 100 mg Tablet", "Allopurinol 300 mg Tablet", "Alprazolam 0.25 mg Tablet", "Alprazolam 0.5 mg Tablet", 
    "Amiloride HCl 5 mg + Hydrochlorothiazide 50 mg Tablet", "Amisulpride 400 mg Tablet", "Amitriptyline HCl 25 mg Tablet", 
    "Amlodipine 5 mg Tablet", "Amlodipine 10 mg Tablet", "Amlodipine 10 mg and Valsartan 160 mg Tablet", 
    "Amlodipine 10mg/Valsartan 160mg/Hydrochlorothiazide 25mg Tab", "Amoxicillin 250mg Capsule", "Amoxicillin 500mg Capsule", 
    "Amoxicillin 250mg/5mL Oral Solution", "Amoxicillin Trihydrate 125 mg/5 ml Syrup", "Amoxicillin 500 mg + Clavulanate 125 mg Tablet", 
    "Amoxicillin + Clavulanate 228 mg/5 ml Syrup", "Amorolfine 5 % Nail Lacquer", "Ampicillin + Sulbactam 375mg Tab", 
    "Apixaban 2.5 mg Film-coated Tablet", "Apixaban 5 mg Film-coated Tablet", "Aqueous Cream", "Aripiprazole 10mg Tablet", 
    "Artificial Tears/Eye Lubricant Ophthalmic Gel", "Artificial Tears/Eye Lubricant Ophthalmic Solution", 
    "Artificial Tears/Eye Lubricant Ophthalmic Solution (Preservative Free)", "Artificial Tears/Eye Lubricant Ophthalmic Solution (Single Use)", 
    "Ascorbic Acid 100 mg Tablet", "Atenolol 50 mg Tablet", "Atenolol 100 mg Tablet", "Atorvastatin 20 mg Tablet", 
    "Atorvastatin 40 mg Tablet", "Atorvastatin 80 mg Tablet", "Atropine Sulphate 1mg/ml Injection", "Atropine Sulphate 1% Eye Drops", 
    "Azathioprine 50 mg Tablet", "Azithromycin 250 mg Tablet", "Baclofen 10 mg Tablet", "BCG Vaccine Freeze-Dried Inj", 
    "Beclomethasone Dipropionate 50 mcg/dose Nasal Spray", "Beclomethasone Dipropionate 100 mcg/dose Inhalation", 
    "Beclomethasone Dipr. 100mcg, Formoterol 6mcg Inhalation", "Benzathine Penicillin 2.4MIU (1.8g) Injection", 
    "Benzhexol 2 mg Tablet", "Benzoic Acid Compound Ointment (Whitfields)", "Benzoyl Peroxide 5% Gel", 
    "Benzydamine HCl 0.15% Solution (Difflam)", "Benzydamine HCl 0.15% Solution (Easiflam)", "Benzyl Benzoate 12.5% Emulsion (Child)", 
    "Benzyl Benzoate 25 % Emulsion (Adult)", "Benzyl Benzoate, Zinc Oxide & Balsam Peru Suppository (Anusol)", 
    "Betahistine Dihydrochloride 24mg Tablet", "Betamethasone 17-Valerate 0.025% (1 in 4) Cream", "Betamethasone 17-Valerate 0.05% (1 in 2) Cream", 
    "Betamethasone 17-Valerate 0.1% Cream", "Betamethasone 17-Valerate 0.1% Ointment", "Betamethasone Valerate 1 in 2 Ointment", 
    "Betamethasone Valerate 1 in 10 Ointment", "Betaxolol 0.25% Eye Suspension", "Bimatoprost 0.03% Ophthalmic Solution", 
    "Bisacodyl 5 mg Tablet", "Bisacodyl 10 mg Suppository", "Bisoprolol Fumarate 2.5 mg Tablet", "Bisoprolol Fumarate 5 mg Tablet", 
    "Brimonidine Tartrate 0.15% Ophthalmic Solution", "Brinzolamide 1%, Brimonidine 0.2% Ophthalmic Suspension", 
    "Bromhexine HCl 4 mg/5 ml Elixir", "Bromhexine HCl 8mg Tablet", "Bromocriptine Mesilate 2.5mg Tablet", "Bromocriptine Mesilate 5mg Tablet", 
    "Budesonide 64mcg Nasal Spray", "Budesonide 100mcg Nasal Spray", "Budesonide 200mcg/dose Inhalation (300 Doses)", 
    "Budesonide Pressurised Inhalation BP 200mcg", "Budesonide 160mcg and Formoterol 4.5mcg Turbuhaler (120doses)", 
    "Calamine Cream", "Calamine Lotion", "Calcipotriol 50 mcg/g + Betamethasone 0.5 mg/g Gel", "Calcipotriol 50 mcg/g + Betamethasone 0.5 mg/g Ointment", 
    "Calcitriol 0.25mcg Capsule", "Calcium Carbonate 500mg Tablet", "Calcium Gluconate 10% Injection", "Calcium Lactate 300mg Tablet", 
    "Calcium Polystyrene Sulphonate Powder, 5g/sachet", "Captopril 25mg Tablet", "Carbamazepine 200mg Tablet", 
    "Carbamazepine 200mg CR Tablet", "Carbamazepine 400mg CR Tablet", "Carbamide (Urea) 10 % Cream", "Carbimazole 5mg Tablet", 
    "Carvedilol 6.25mg Tablet", "Celecoxib 200mg Capsule", "Cephalexin Monohydrate 250mg Capsule", "Cephalexin Monohydrate 500mg Capsule", 
    "Ceftriaxone 500mg Injection", "Cefuroxime Axetil 125mg Tablet", "Cetirizine HCl 10mg Tablet", "Cetrimide 2% Lotion", 
    "Charcoal Activated 250mg Tablet", "Chloramphenicol 0.5% Eye Drops", "Chloramphenicol 1% Eye Ointment", "Chloramphenicol 5% w/v Ear Drops", 
    "Chlorhexidine 1:200 in Alcohol with Emollient", "Chlorhexidine 1 in 200 (0.5%) in Alcohol 70%", "Chlorhexidine 1 in 2000 (0.05%) in Alcohol 70%", 
    "Chlorhexidine Gluconate 0.2% Mouthwash", "Chlorhexidine Gluconate 5% Solution", "Chlorhexidine gluconate 1% Cream (Obstetric)", 
    "Chlorpheniramine Maleate 2 mg/5 ml Syrup", "Chlorpheniramine Maleate 4mg Tablet", "Chlorpheniramine 10mg/ml Injection", 
    "Chlorpromazine HCl 25 mg Tablet", "Chlorpromazine HCl 100 mg Tablet", "Cholecalciferol 25,000 IU per 1ml Oral Solution", 
    "Cinnarizine 25 mg Tablet", "Clobetasol Propionate 0.05% Cream", "Clobetasol Propionate 0.05% Ointment", 
    "Clobetasone Butyrate 0.05% Cream", "Clobetasone Butyrate 0.05% Ointment", "Clopidogrel 75 mg Tablet", 
    "Clotrimazole 1% Cream", "Clotrimazole 500 mg Vaginal Tablet", "Clozapine 100 mg Tablet", "Cloxacillin Sodium 125 mg/5 ml Suspension", 
    "Cloxacillin Sodium 250mg Capsule", "Cloxacillin 500mg Capsule", "Coal Tar (LPC) 3% Ointment", "Coal Tar (LPC) 6% Ointment", 
    "Coal Tar 12% Salicylic acid 2% Sulphur 4% Ointment", "Colchicine 0.5 mg Tablet", "Compound Zinc Paste BP (25%w/w)", 
    "Conjugated Oestrogens 0.625mg Tablet", "Copper Sulphate Crystal", "Crotamiton 10 % Cream", "Dabigatran Etexilate 110 mg Capsule", 
    "Dabigatran Etexilate 150 mg Capsule", "Daclatasvir 60mg Tablet", "Danazol 200 mg Capsule", "Dapagliflozin 10 mg Film-Coated Tablet", 
    "Dapsone 100 mg Tablet", "Desloratadine 5 mg Tablet", "Desvenlafaxine 50 mg EXTENDED RELEASE Tablet", "Dexamethasone Acetate 0.1% Eye Drop", 
    "Dexamethasone sodium phosphate 0.1% Eye Drops", "Dexamethasone,Neomycin,Polymyxin B Eye Drop (Maxitrol)", 
    "Dextrose 5% 500ml IV soln", "Dextrose 10% 500mL IV soln", "Dextrose 50% 10mL Inj", "Dextrose Powder", 
    "Diazepam 5 mg Rectal Solution", "Diazepam 10 mg/2 ml Injection", "Diclofenac 1% Emulgel", "Diclofenac Sodium 50 mg Tablet", 
    "Diclofenac Sodium 75mg/3 ml Injection", "Dienogest 2mg Tablet", "Digoxin 0.25 mg Tablet", "Diltiazem HCl 30 mg Tablet", 
    "Diosmin 450 mg and Hesperidin 50 mg Tablet", "Diphenhydramine HCl Expectorant (Adult)", "Diphenhydramine HCl Expectorant (Paediatric) 7mg/5ml", 
    "Diphenoxylate with Atropine Sulphate Tablet", "Diphtheria and Tetanus Vaccine", "Diptheria-Tetanus-Pertussis-IPV-Hib Vaccine", 
    "Distilled Water", "Dolutegravir 50 mg Tablet", "Domperidone 1 mg/ml Suspension", "Domperidone 10 mg Tablet", 
    "Donepezil HCl 5 mg Tablet", "Donepezil HCl 10 mg Tablet", "Dorzolamide HCl 2% Ophthalmic Solution", 
    "Dorzolamide 2%, Timolol 0.5% Eye drop", "Doxazosin Mesilate 4 mg CR Tablet", "Doxycycline 100 mg Capsule", 
    "Duloxetine 60 mg Capsule", "Dutasteride 0.5 mg Capsule", "Dutasteride 0.5mg and Tamsulosin 0.4mg Capsule", 
    "Dydrogesterone 10 mg Tablet", "Ear Wax Softener (Ear Drop)", "Efavirenz 200 mg Capsule/Tablet", "Efavirenz 600 mg Tablet", 
    "Empagliflozin 10 mg Tablet", "Empagliflozin 25 mg Tablet", "Emulsifying Ointment BP", "Enalapril 5 mg Tablet", 
    "Enalapril 10 mg Tablet", "Enalapril 20 mg Tablet", "Enoxaparin Sodium 20 mg Injection", "Enoxaparin Sodium 60 mg Injection", 
    "Entacapone 200 mg Tablet", "Eperisone HCl 50 mg Tablet", "Erythromycin Ethylsuccinate 200 mg/5 ml Suspension", 
    "Erythromycin Ethylsuccinate 400 mg Tablet", "Escitalopram 10 mg Tablet", "ESOMEprazole 40 mg Tablet", 
    "Estradiol 2mg + Norgestrel 0.5mg (Combo Pack)", "Ethambutol HCl 400 mg Tablet", "Ethinyloestradiol 30mcg + Levonorgestrel 150mcg Tab", 
    "Etonogestrel 68 mg Implant", "Etoricoxib 90 mg Tablet", "Etoricoxib 120 mg Tablet", "Ezetimibe 10 mg Tablet", 
    "Ezetimibe 10 mg + Simvastatin 20 mg Tablet", "Felodipine 10 mg EXTENDED RELEASE Tablet", "Fenofibrate 145mg Tablet", 
    "Fentanyl 25 mcg/h Transdermal Patch", "Ferric Ammonium Citrate 400mg/5ml (FAC)", "Ferrous 350mg, Folic 1mg, Vit C, B6, B12, Zinc Capsule", 
    "Ferrous CR 525mg, Folic 800mcg, Vit C, B-Complex Tablet", "Ferrous Fumarate 200 mg Tablet", 
    "Ferrous Iron (Elemental Iron > 100mg), Vitamin & Mineral Capsule", "Finasteride 5 mg Tablet", "Fluconazole 100 mg Capsule", 
    "Fludrocortisone Acetate 0.1 mg Tablet", "Flunarizine HCl 5 mg Capsule", "Fluoxetine HCl 20 mg Capsule/Tablet", 
    "Flupenthixol Decanoate Depot 20mg/ml lnjection", "Fluphenazine Decanoate 25mg/ml Inj", "Fluticasone Furoate 27.5 mcg/dose Nasal Spray (60 doses)", 
    "Fluticasone Furoate 27.5 mcg/dose Nasal Spray (120 doses)", "Fluticasone propionate 125 mcg/dose Evohaler (120doses)", 
    "Fluticasone Propionate 125 mcg/dose Inhalation (120doses)", "Fluvoxamine 50 mg Tablet", "Fluvoxamine 100 mg Tablet", 
    "Folic Acid 5 mg Tablet", "Frusemide 10mg/ml Injection (20mg/2ml)", "Frusemide 40 mg Tablet", "Fusidic Acid 2% Cream", 
    "Fusidic Acid 1% Eye Drops", "Fusidic Acid 2% in Betamethasone Valerate 0.1% Cream", "Gabapentin 300 mg Capsule", 
    "Gabapentin 600 mg Tablet", "Gamma Benzene Hexachloride 0.1 % Lotion", "Gamma Benzene Hexachloride 1% Lotion", 
    "Gemfibrozil 300 mg Capsule", "Glibenclamide 5 mg Tablet", "Gliclazide 30 mg MODIFIED RELEASE Tablet", 
    "Gliclazide 60 mg MODIFIED RELEASE Tablet", "Gliclazide 80 mg Tablet", "Glycerin (Liquid)", "Glycerine 25% in Aqueous Cream", 
    "Glycerin 25%, Sodium Chloride 15% Enema (Ravin)", "Glyceryl Trinitrate 0.5 mg Tablet", 
    "Glycopyrronium 50mcg Inhalation Powder Hard Capsules", "Griseofulvin 125mg Tablet", "Haloperidol 1.5 mg Tablet",
